### PR TITLE
release 2.0.0

### PR DESCRIPTION
**Pull request by esarafianou**
### Description

1. Prepares for release 2.0.0, which drops support for Node 8. 
2. Also updates package lock file to version 2 which is [backwards compatible to version 1](https://docs.npmjs.com/cli/v8/configuring-npm/package-lock-json#lockfileversion)

### CODE REVIEW

**Review by radekk — DISMISSED** [review]
👍🏻

**Review by gkwang — CHANGES_REQUESTED** [review]
Can we update this as well:
https://github.com/auth0/node-xml-encryption/blob/291f3f10d5d1d571a3b6da2d411aa323398f5650/package.json#L35

**Comment by gkwang** [comment]
nit: Also do we want to keep the package-lock file since this is a library?

**Review by gkwang — APPROVED** [review]
Sounds good. I think we can leave the package-lock around to make some of our tools happy.

**Pull request merged**
