### PR TITLE
Update xpath, xmldom, y18n, lodash

### PR DESCRIPTION
**Pull request by LoneRifle**
By submitting a PR to this repository, I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Routine upgrade of the abovementioned dependencies to bring it in-line with xml-crypto, so that projects that depend on both packages would keep transitive dependencies to a minimum.

### Testing

Relying on CI tests

### Checklist

- [x] I have added documentation for new/changed functionality in this PR or in auth0.com/docs
- [x] All active GitHub checks for tests, formatting, and security are passing
- [x] The correct base branch is being used, if not `master`

### CODE REVIEW

**Review by esarafianou — APPROVED** [review]
LGTM

**Comment by esarafianou** [comment]
Thank you for the PR!

**Comment by esarafianou** [comment]
@LoneRifle The repository requires that the commits are signed. Could you please sign them and push them?

**Comment by LoneRifle** [comment]
Will do, just give me a while

**Comment by LoneRifle** [comment]
@esarafianou - signed the commit as requested. Hope to see the reapproval and merge in due course!

**Review by gkwang — APPROVED** [review]

**Pull request merged**
