### PR TITLE
Remove test files from module build 

### PR DESCRIPTION
**Pull request by dosullivan557**
By submitting a PR to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md). Please see the [contributing guidelines](https://github.com/auth0/.github/blob/master/CONTRIBUTING.md) for how to create and submit a high-quality PR for this repo.

### Description

> Describe the purpose of this PR along with any background information and the impacts of the proposed change. For the benefit of the community, please do not assume prior context.
>
> Provide details that support your chosen implementation, including: breaking changes, alternatives considered, changes to the API, etc.
>
> If the UI is being changed, please provide screenshots.

### References

> Include any links supporting this change such as a:
>
> - GitHub Issue/PR number addressed or fixed
> - Auth0 Community post
> - StackOverflow post
> - Support forum thread
> - Related pull requests/issues from other repos
>
> If there are no references, simply delete this section.

### Testing

> Describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors.
>
> Please include any manual steps for testing end-to-end or functionality not covered by unit/integration tests.
>
> Also include details of the environment this PR was developed in (language/platform/browser version).

- [x] This change adds test coverage for new/changed/fixed functionality

### Checklist

- [x] I have added documentation for new/changed functionality in this PR or in auth0.com/docs
- [x] All active GitHub checks for tests, formatting, and security are passing
- [x] The correct base branch is being used, if not `master`

### CODE REVIEW

**Comment by dosullivan557** [comment]
Hi @ja30278 @pol @chrisscott @jstrutz - could you review this pr please.

I install your module in an application, it copies over .pem and .key files that are in your tests. This means that when we put our application through security scans, it fails because it finds these files and classifies them as sensitive data. What I'm asking is whether you can not include these in the bundled version of the application.

To resolve it, you can have a section in the package.json that doesn't pull the test files over to the build of the module when it is pulled in.

**Comment by gkwang** [comment]
Hi @dosullivan557, changes look good. Do you mind signing the commit since we have that enabled in order to merge the changes. 
I'll get it merged as soon as that's done.  

Thanks for the contribution!

**Comment by dosullivan557** [comment]
Hey @gkwang - I pushed a signed commit up - lemme know if there's anything else

**Comment by dosullivan557** [comment]
Hey @gkwang  - any update on this?

**Review by gkwang — APPROVED** [review]

**Comment by gkwang** [comment]
@dosullivan557, Sorry I missed your last message.  All commits needs to be signed, so you'll need to squash the commits and sign it.

**Comment by dosullivan557** [comment]
Hi @gkwang - I was getting into a bit of a mess, so decided to start again with a fresh PR - see the please see PR #80

**Pull request closed without merging**
