### PR TITLE
Fix for Okta encrypted assertion

### PR DESCRIPTION
**Pull request by deepakprabhakara**
By submitting a PR to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md). Please see the [contributing guidelines](https://github.com/auth0/.github/blob/master/CONTRIBUTING.md) for how to create and submit a high-quality PR for this repo.

### Description

Okta encrypted assertion is slightly different from spec, the keyInfo is not under the default namespace. Also updates dependencies.

### Testing

This change passes all existing test coverage. Tricky to add Okta's encrypted assertion without leaking our account's info.

### Checklist

- [x] I have added documentation for new/changed functionality in this PR or in auth0.com/docs
- [x] All active GitHub checks for tests, formatting, and security are passing
- [x] The correct base branch is being used, if not `master`

### CODE REVIEW

**Comment by gkwang** [comment]
@deepakprabhakara do you have an example of your failed okta assertion? I don't see how the KeyInfo would be null with my test Okta assertion.

**Comment by deepakprabhakara** [comment]
@gkwang You can use the one here - https://github.com/boxyhq/saml20/tree/main/test/assets/certificates, it's been created with a throwaway email account so my original comment about difficulty adding a test is not valid anymore. Shall I add a test?

**Comment by gkwang** [comment]
@deepakprabhakara  Ah I see. Yes that'd be great.

**Comment by deepakprabhakara** [comment]
@gkwang done

**Review by gkwang — DISMISSED** [review]

**Comment by gkwang** [comment]
@deepakprabhakara  Can you sign your commit?

**Comment by deepakprabhakara** [comment]
@gkwang Will do that shortly

**Review by gkwang — DISMISSED** [review]

**Comment by deepakprabhakara** [comment]
@gkwang Signed the last couple of dummy commits, happy to create a new PR if that's easier?

**Comment by gkwang** [comment]
Yeah either create a new PR, or you'll need to squash and sign the commit.

**Review by gkwang — APPROVED** [review]

**Comment by gkwang** [comment]
Still a no go with your latest push FYI 
image

**Comment by deepakprabhakara** [comment]
Will open a new PR shortly.

**Comment by deepakprabhakara** [comment]
New PR - https://github.com/auth0/node-xml-encryption/pull/105, thanks @gkwang

**Pull request closed without merging**
